---
- set_fact:
    go_use_binary: "{{ go_checksums[go_os] is defined and go_checksums[go_os][go_arch] is defined }}"

- file:
    state: directory
    path: "/home/peon/godev/go{{ go_version }}"
    owner: peon
    group: peon

- name: Fetch distribution tarball
  become: yes
  become_user: peon
  get_url:
    url: "https://dl.google.com/go/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz"
    dest: /tmp/
    checksum: "sha256:{{ go_checksums[go_os][go_arch] }}"
  when: go_use_binary

- name: Extract Go into peon home dir
  become: yes
  become_user: peon
  unarchive:
    src: "/tmp/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz"
    dest: "/home/peon/godev/go{{ go_version }}"
    copy: no
  when: go_use_binary

- name: Fetch src tree
  become: yes
  become_user: peon
  git:
    repo: https://github.com/golang/go/
    dest: "/home/peon/godev/go{{ go_version }}/go"
    depth: 1
    version: "go{{ go_version }}"
  when: not go_use_binary

- name: Build src
  become: yes
  become_user: peon
  shell: ./make.bash
  args:
    chdir: "/home/peon/godev/go{{ go_version }}/go/src"
  when: not go_use_binary

- name: Link to extracted version
  file:
    state: link
    owner: peon
    group: peon
    src: "/home/peon/godev/go{{ go_version }}/go"
    dest: "/home/peon/godev/go"

- name: Export GOROOT
  lineinfile:
    dest: /home/peon/.profile
    create: yes
    owner: peon
    group: peon
    mode: 0664
    regexp: '^export GOROOT'
    line: 'export GOROOT="/home/peon/godev/go"'

- name: GOROOT bin in path
  lineinfile:
    dest: /home/peon/.profile
    create: yes
    owner: peon
    group: peon
    mode: 0664
    regexp: '^export PATH=["]?[$]GOROOT'
    line: 'export PATH="$GOROOT/bin:$PATH"'
