---
- set_fact:
    platform: "{{ lookup('env','PACKER_TEMPLATE') | regex_replace('[^a-zA-Z0-9-]', '-') }}"

- set_fact:
    hostname: "{{ platform }}.build.prometheus.io"

# This is a common way for all platforms to bootstrap servies
- lineinfile:
    dest: /etc/rc.local
    create: yes
    owner: root
    group: "{{ root_group }}"
    mode: 0775
    regexp: '^[#][!]'
    line: '#!/bin/sh'
    insertbefore: BOF
