---

- name: Update to latest patch level
  shell: freebsd-update fetch --not-running-from-cron || freebsd-update install || true

- name: Remove pkg directory
  file:
    state: absent
    path: /usr/local/etc/pkg

- name: Update pkg database
  shell: IGNORE_OSVERSION=yes pkg update -f

- name: Install or upgrade required packages
  shell: pkg install -y python go gmake git-lite bash curl tmux sudo gtar

- name: Set hostname 1/2 - hostname
  shell: "hostname {{ hostname }}"

- name: Set hostname 2/2 - /etc/rc.conf
  lineinfile:
    dest: /etc/rc.conf
    create: yes
    owner: root
    group: "{{ root_group }}"
    mode: 664
    regexp: '^hostname'
    line: "hostname=\"{{ hostname }}\""

# configure bash
- lineinfile:
    dest: /etc/fstab
    create: yes
    owner: root
    group: "{{ root_group }}"
    mode: 664
    regexp: '^fdesc'
    line: 'fdesc /dev/fd fdescfs rw 0 0'

- name: Mount fdesc filesystem
  shell: mount /dev/fd

